In [1]:
from scipy.io import loadmat
import numpy as np

In [3]:
mat = loadmat(r'D:\Desktop\Grab Computer Vision\car_devkit\devkit\cars_meta.mat')

In [9]:
type(mat)

dict

In [10]:
mat.keys()

dict_keys(['__header__', '__version__', '__globals__', 'class_names'])

In [11]:
mat['__header__']

b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Sat Dec 14 14:13:07 2013'

In [12]:
mat['__globals__']

[]

In [14]:
mat['class_names']

array([[array(['AM General Hummer SUV 2000'], dtype='<U26'),
        array(['Acura RL Sedan 2012'], dtype='<U19'),
        array(['Acura TL Sedan 2012'], dtype='<U19'),
        array(['Acura TL Type-S 2008'], dtype='<U20'),
        array(['Acura TSX Sedan 2012'], dtype='<U20'),
        array(['Acura Integra Type R 2001'], dtype='<U25'),
        array(['Acura ZDX Hatchback 2012'], dtype='<U24'),
        array(['Aston Martin V8 Vantage Convertible 2012'], dtype='<U40'),
        array(['Aston Martin V8 Vantage Coupe 2012'], dtype='<U34'),
        array(['Aston Martin Virage Convertible 2012'], dtype='<U36'),
        array(['Aston Martin Virage Coupe 2012'], dtype='<U30'),
        array(['Audi RS 4 Convertible 2008'], dtype='<U26'),
        array(['Audi A5 Coupe 2012'], dtype='<U18'),
        array(['Audi TTS Coupe 2012'], dtype='<U19'),
        array(['Audi R8 Coupe 2012'], dtype='<U18'),
        array(['Audi V8 Sedan 1994'], dtype='<U18'),
        array(['Audi 100 Sedan 1994'], dtype='<U

In [15]:
type(mat['class_names'])

numpy.ndarray

In [17]:
class_names = mat['class_names']

In [18]:
class_names.shape

(1, 196)

In [24]:
class_names[0][0]

array(['AM General Hummer SUV 2000'], dtype='<U26')

In [25]:
class_names[0][0][0] #Seems like this is what we want

'AM General Hummer SUV 2000'

In [30]:
#Get all the class names
class_name_list = []
for i in range(196):
    class_name_list.append(class_names[0][i][0])

In [31]:
#See class names
class_name_list

['AM General Hummer SUV 2000',
 'Acura RL Sedan 2012',
 'Acura TL Sedan 2012',
 'Acura TL Type-S 2008',
 'Acura TSX Sedan 2012',
 'Acura Integra Type R 2001',
 'Acura ZDX Hatchback 2012',
 'Aston Martin V8 Vantage Convertible 2012',
 'Aston Martin V8 Vantage Coupe 2012',
 'Aston Martin Virage Convertible 2012',
 'Aston Martin Virage Coupe 2012',
 'Audi RS 4 Convertible 2008',
 'Audi A5 Coupe 2012',
 'Audi TTS Coupe 2012',
 'Audi R8 Coupe 2012',
 'Audi V8 Sedan 1994',
 'Audi 100 Sedan 1994',
 'Audi 100 Wagon 1994',
 'Audi TT Hatchback 2011',
 'Audi S6 Sedan 2011',
 'Audi S5 Convertible 2012',
 'Audi S5 Coupe 2012',
 'Audi S4 Sedan 2012',
 'Audi S4 Sedan 2007',
 'Audi TT RS Coupe 2012',
 'BMW ActiveHybrid 5 Sedan 2012',
 'BMW 1 Series Convertible 2012',
 'BMW 1 Series Coupe 2012',
 'BMW 3 Series Sedan 2012',
 'BMW 3 Series Wagon 2012',
 'BMW 6 Series Convertible 2007',
 'BMW X5 SUV 2007',
 'BMW X6 SUV 2012',
 'BMW M3 Coupe 2012',
 'BMW M5 Sedan 2010',
 'BMW M6 Convertible 2010',
 'BMW X3

In [5]:
mat = loadmat(r'D:\Desktop\Grab Computer Vision\car_devkit\devkit\cars_train_annos.mat')

In [63]:
mat.keys()

dict_keys(['__header__', '__version__', '__globals__', 'annotations'])

In [64]:
type(mat['annotations'])

numpy.ndarray

In [65]:
mat['annotations'].shape

(1, 8144)

In [66]:
type(mat['annotations'][0][0])

numpy.void

In [67]:
mat['annotations'][0][1]

(array([[36]], dtype=uint8), array([[116]], dtype=uint8), array([[868]], dtype=uint16), array([[587]], dtype=uint16), array([[3]], dtype=uint8), array(['00002.jpg'], dtype='<U9'))

In [73]:
mat['annotations'][0][2][4]

array([[91]], dtype=uint8)

In [83]:
# Save the label - type of car
labels = []
for i in range(8144):
    labels.append(mat['annotations'][0][i][4][0])

In [81]:
from sklearn.preprocessing import MultiLabelBinarizer

In [84]:
mlb = MultiLabelBinarizer()
labels = mlb.fit_transform(labels) #Change labels to one-hot for training

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [86]:
#Save labels to disk for ease of use
labels = np.array(labels)
np.save("y.npy", labels)

In [120]:
#Create data folder and subdirectories for each class
import os
current_directory = os.getcwd()
data_directory = os.path.join(current_directory, "data")
os.mkdir(data_directory)
for i in range(len(class_name_list)):
    class_directory = os.path.join(data_directory, str(i+1)) #Class metadata range from 1 to 196
    os.mkdir(class_directory)

In [121]:
import shutil
#Move training images to appropriate directories
for i in range(8144):
    image_src = os.path.join(current_directory, "cars_train", "cars_train", str(mat['annotations'][0][i][5][0]))
    image_dst = os.path.join(data_directory, str(mat['annotations'][0][i][4][0][0]))
    shutil.copy(image_src, image_dst)

In [10]:
print(str(mat['annotations'][0][6][4][0][0]))

89
